"use client"
import Image from "next/image"
import Link from "next/link"
import { ExternalLink, GitCompareArrows } from "lucide-react"
import { products, lowestOffer } from "@/data/products"
import { formatPrice } from "@/lib/format"
import { useStore } from "@/components/providers/store-provider"
import { Button } from "@/components/ui/button"
export default function ComparePage(){ const {compare,ready,removeCompare,clearCompare}=useStore(); const items=ready?products.filter(p=>compare.includes(p.id)):[]; if(items.length<2) return <div className="mx-auto max-w-5xl px-4 py-12 text-center sm:px-6"><GitCompareArrows className="mx-auto size-10 text-muted-foreground"/><h1 className="mt-4 font-display text-3xl font-bold">Compare products</h1><p className="mt-2 text-muted-foreground">Add at least two products to compare prices and specifications.</p><Button asChild className="mt-6 rounded-full"><Link href="/products">Browse products</Link></Button></div>; const specKeys=Array.from(new Set(items.flatMap(p=>Object.keys(p.specifications)))).slice(0,8); return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="mb-7 flex items-center justify-between"><div><h1 className="font-display text-3xl font-bold">Compare products</h1><p className="text-muted-foreground">Side-by-side demo comparison</p></div><Button variant="outline" onClick={clearCompare}>Clear all</Button></div><div className="overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[720px] text-sm"><tbody><tr><th className="w-40 bg-secondary/30 p-4 text-left">Product</th>{items.map(p=><td key={p.id} className="p-4 align-top"><div className="relative mb-3 aspect-square max-w-40"><Image src={p.images[0]} alt={p.name} fill className="object-contain"/></div><Link href={`/product/${p.slug}`} className="font-display font-semibold hover:text-brand">{p.name}</Link><button onClick={()=>removeCompare(p.id)} className="mt-2 block text-xs text-muted-foreground hover:text-foreground">Remove</button></td>)}</tr><Row label="Best price" values={items.map(p=>formatPrice(lowestOffer(p).price))}/><Row label="Rating" values={items.map(p=>`${p.rating}/5 (${p.reviewCount.toLocaleString()})`)}/><Row label="Best store" values={items.map(p=>lowestOffer(p).store)}/>{specKeys.map(k=><Row key={k} label={k} values={items.map(p=>p.specifications[k]||"—")}/>) }<tr><th className="bg-secondary/30 p-4 text-left">Deal</th>{items.map(p=>{const o=lowestOffer(p);return <td key={p.id} className="p-4"><Button asChild size="sm" className="rounded-full"><a href={o.affiliateUrl} target="_blank" rel="nofollow sponsored noopener noreferrer">View deal <ExternalLink className="size-3.5"/></a></Button></td>})}</tr></tbody></table></div></div>}
function Row({label,values}:{label:string;values:string[]}){return <tr className="border-t border-border"><th className="bg-secondary/30 p-4 text-left font-medium">{label}</th>{values.map((v,i)=><td key={i} className="p-4">{v}</td>)}</tr>}
